# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Skyline DataMiner Deploy Action
        # You may pin to the exact commit or the version.
        # uses: SkylineCommunications/Skyline-DataMiner-Deploy-Action@a1b280087cc1929842b7b1f1f7a40831f9942ec2
        uses: SkylineCommunications/Skyline-DataMiner-Deploy-Action@v1.0.12
        with:
          # The API-key generated in the DCP Admin app as authentication for a certain DataMiner System, saved in a GitHub secret
          api-key: ${{ secrets.DATAMINER_DEPLOY_KEY }}
          # The path to the .sln file of the solution. Atm only DataMiner Automation Script solutions are supported. E.g ./Example/AutomationScript.sln. Required for stages: All and Upload.
          solution-path: AutomationScript.sln
          # The chosen name of the artifact. E.g. MyPackageName.  Required for stages: All, Upload and Deploy.
          artifact-name: Empower_WouterVA # optional
          # The version number for the artifact. Only required for a release run. (format A.B.C). E.g. 1.0.1. Required for stages Upload and All if no build number was provided instead.
          version: 1.0.1 # optional
          # The build number of a workflow run. Only required for a development run. Required for stages Upload and All if no version was provided instead.
          build-number:  ${{ github.run_number }} # optional

